# Generated by Django 4.0.6 on 2022-08-20 08:53

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Name of the event')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Date of event')),
                ('time', models.TimeField(blank=True, null=True, verbose_name='Time of event')),
                ('description', tinymce.models.HTMLField(null=True)),
                ('price', models.FloatField(verbose_name='Price')),
                ('max_players', models.IntegerField(verbose_name='Maximum player number')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(blank=True, choices=[('a', 'active'), ('i', 'inactive')], default='a', help_text='Statusas', max_length=1)),
            ],
            options={
                'verbose_name': 'Event',
                'verbose_name_plural': 'Events',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Name of the game field')),
                ('location_long', models.FloatField(max_length=50, null=True, verbose_name='Location longitude')),
                ('location_lat', models.FloatField(max_length=50, null=True, verbose_name='Location latitude')),
                ('description', tinymce.models.HTMLField(blank=True, null=True)),
                ('field_map', models.ImageField(default='default_map.png', upload_to='maps/')),
            ],
            options={
                'verbose_name': 'Field',
                'verbose_name_plural': 'Fields',
            },
        ),
        migrations.CreateModel(
            name='Organizer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='New Organizer', max_length=150, verbose_name='Name of the organizer')),
                ('profile_picture', models.ImageField(default='default.png', upload_to='organizer_pics/')),
                ('contacts', models.CharField(max_length=150, verbose_name='Address and contacts')),
                ('description', tinymce.models.HTMLField(null=True)),
            ],
            options={
                'verbose_name': 'Organizer',
                'verbose_name_plural': 'Organizers',
            },
        ),
    ]
