# Generated by Django 4.0.6 on 2022-08-11 18:25

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organizer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='New Organizer', max_length=150, verbose_name='Name of the organizer')),
                ('profile_picture', models.ImageField(default='defaulf.png', upload_to='organizer_pics/')),
                ('contacts', models.CharField(max_length=150, verbose_name='Address and contacts')),
                ('description', tinymce.models.HTMLField(null=True)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='organizer', to='teams.profile')),
            ],
            options={
                'verbose_name': 'Organizer',
                'verbose_name_plural': 'Organizers',
            },
        ),
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Name of the game field')),
                ('location_long', models.FloatField(max_length=50, null=True, verbose_name='Location longitude')),
                ('location_lat', models.FloatField(max_length=50, null=True, verbose_name='Location latitude')),
                ('description', tinymce.models.HTMLField(blank=True, null=True)),
                ('field_map', models.ImageField(default='defaulf_map.png', upload_to='maps/')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='field_organizers', to='events.organizer')),
            ],
            options={
                'verbose_name': 'Field',
                'verbose_name_plural': 'Fields',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Name of the event')),
                ('date', models.DateTimeField(blank=True, null=True, verbose_name='Date of event')),
                ('description', tinymce.models.HTMLField(null=True)),
                ('price', models.FloatField(verbose_name='Price')),
                ('max_players', models.IntegerField(verbose_name='Maximum player number')),
                ('registered_players', models.IntegerField(default=0, verbose_name='Registered player number')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('field', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='events.field')),
                ('organizer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_organizers', to='events.organizer')),
            ],
            options={
                'verbose_name': 'Event',
                'verbose_name_plural': 'Events',
            },
        ),
    ]
