# Generated by Django 4.0.6 on 2022-07-19 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Name of the event')),
                ('date', models.DateTimeField(blank=True, null=True, verbose_name='Date of event')),
                ('price', models.FloatField(verbose_name='Price')),
                ('max_players', models.IntegerField(verbose_name='Maximum player number')),
                ('registered_players', models.IntegerField(verbose_name='Registered player number')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Event',
                'verbose_name_plural': 'Events',
            },
        ),
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Name of the game field')),
                ('location', models.CharField(max_length=50, verbose_name='Location coordinates')),
                ('field_map', models.ImageField(null=True, upload_to='maps', verbose_name='Image of the map')),
            ],
            options={
                'verbose_name': 'Field',
                'verbose_name_plural': 'Fields',
            },
        ),
        migrations.CreateModel(
            name='Organizer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Name of the organizer')),
                ('contacts', models.CharField(max_length=150, verbose_name='Address and contacts')),
                ('events', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event', to='events.event')),
                ('fields', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='field', to='events.field')),
            ],
            options={
                'verbose_name': 'Organizer',
                'verbose_name_plural': 'Organizers',
            },
        ),
        migrations.AddField(
            model_name='event',
            name='field',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='events.field'),
        ),
    ]
