# Generated by Django 4.0.6 on 2022-07-26 14:43

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='description',
            field=tinymce.models.HTMLField(null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='organizer',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='events.organizer'),
        ),
        migrations.AddField(
            model_name='field',
            name='description',
            field=tinymce.models.HTMLField(null=True),
        ),
        migrations.AddField(
            model_name='organizer',
            name='description',
            field=tinymce.models.HTMLField(null=True),
        ),
        migrations.AddField(
            model_name='organizer',
            name='email',
            field=models.EmailField(max_length=150, null=True, verbose_name='Email of organizer'),
        ),
        migrations.AlterField(
            model_name='field',
            name='field_map',
            field=models.ImageField(null=True, upload_to='events/static/maps', verbose_name='Image of the map'),
        ),
    ]
