# Generated by Django 4.0.6 on 2022-08-03 17:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0002_alter_player_profile'),
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizer',
            name='profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='organizer', to='teams.profile'),
        ),
    ]
