# Generated by Django 4.0.6 on 2022-08-15 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_alter_field_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='field',
            name='field_map',
            field=models.ImageField(default='default_map.png', upload_to='maps/'),
        ),
    ]
