# Generated by Django 4.0.6 on 2022-08-09 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_alter_organizer_name_alter_organizer_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='registered_players',
            field=models.IntegerField(default=0, verbose_name='Registered player number'),
        ),
    ]
