# Generated by Django 4.0.6 on 2022-07-26 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_event_description_event_organizer_field_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='field',
            name='location',
        ),
        migrations.AddField(
            model_name='field',
            name='location_lat',
            field=models.CharField(max_length=50, null=True, verbose_name='Location latitude'),
        ),
        migrations.AddField(
            model_name='field',
            name='location_long',
            field=models.CharField(max_length=50, null=True, verbose_name='Location longitude'),
        ),
    ]
