# Generated by Django 4.0.6 on 2022-08-04 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_alter_organizer_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organizer',
            old_name='picture',
            new_name='o_picture',
        ),
    ]
