# Generated by Django 4.0.6 on 2022-08-04 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_rename_picture_organizer_o_picture'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organizer',
            old_name='o_picture',
            new_name='picture',
        ),
    ]
