# Generated by Django 4.0.6 on 2022-07-27 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_alter_event_field_alter_event_organizer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='field',
            name='field_map',
            field=models.ImageField(null=True, upload_to='../events/static/maps', verbose_name='Image of the map'),
        ),
    ]
