# Generated by Django 4.0.6 on 2022-08-18 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_remove_event_registered_players'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizer',
            name='profile_picture',
            field=models.ImageField(default='default.png', upload_to='organizer_pics/'),
        ),
    ]
