# Generated by Django 4.0.6 on 2022-08-21 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_alter_event_description_alter_event_field_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizer',
            name='profile_picture',
            field=models.ImageField(default='default.png', upload_to='organizer_pics/', verbose_name='Profile picture'),
        ),
    ]
