# Generated by Django 4.0.6 on 2022-08-22 10:04

from django.db import migrations, models
import events.models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_alter_organizer_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='field',
            field=models.ForeignKey(help_text='Field', null=True, on_delete=events.models.Field.get_default_field_pk, related_name='field_event', to='events.field'),
        ),
    ]
