# Generated by Django 4.0.6 on 2022-07-27 17:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_remove_organizer_fields_alter_field_field_map'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organizer',
            name='events',
        ),
        migrations.AlterField(
            model_name='event',
            name='organizer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_organizers', to='events.organizer'),
        ),
    ]
