# Generated by Django 4.0.6 on 2022-08-22 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_alter_event_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='field',
            field=models.ForeignKey(help_text='Field', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='field_event', to='events.field'),
        ),
    ]
