# Generated by Django 4.0.6 on 2022-08-22 11:03

from django.db import migrations, models
import django.db.models.deletion
import events.models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_alter_event_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='field',
            field=models.ForeignKey(default=events.models.Field.get_default_field_pk, help_text='Field', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='field_event', to='events.field'),
        ),
    ]
