# Generated by Django 4.0.6 on 2022-08-21 12:06

from django.db import migrations, models
import django.db.models.deletion
import teams.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_alter_event_description_alter_event_field_and_more'),
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='games_played',
        ),
        migrations.AlterField(
            model_name='player',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True, verbose_name='Date of birth'),
        ),
        migrations.AlterField(
            model_name='player',
            name='events',
            field=models.ManyToManyField(blank=True, help_text='Events', related_name='registered_players', to='events.event'),
        ),
        migrations.AlterField(
            model_name='player',
            name='picture',
            field=models.ImageField(default='default.png', upload_to='profile_pics/', verbose_name='Picture'),
        ),
        migrations.AlterField(
            model_name='player',
            name='team',
            field=models.ForeignKey(default=teams.models.Team.get_default_pk, help_text='Team', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='players', to='teams.team'),
        ),
        migrations.AlterField(
            model_name='team',
            name='contacts',
            field=models.CharField(max_length=150, verbose_name='Contacts'),
        ),
        migrations.AlterField(
            model_name='team',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, help_text='Unique team ID', primary_key=True, serialize=False),
        ),
    ]
