# Generated by Django 4.0.6 on 2022-07-27 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0003_alter_player_team'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='players',
        ),
        migrations.AddField(
            model_name='team',
            name='players',
            field=models.ManyToManyField(blank=True, null=True, related_name='players', to='teams.player'),
        ),
    ]
