# Generated by Django 4.0.6 on 2022-08-04 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0003_rename_picture_player_p_picture'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='p_picture',
            new_name='picture',
        ),
    ]
