# Generated by Django 4.0.6 on 2022-08-08 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0004_rename_p_picture_player_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='games_played',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='n_name',
            field=models.CharField(default='self.profile.user.username', max_length=150, verbose_name='Nickname of the player'),
        ),
    ]
