# Generated by Django 4.0.6 on 2022-08-08 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0006_alter_player_n_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='picture',
            field=models.ImageField(default='events/static/media/defaulf.png', upload_to='events/static/profile_pics'),
        ),
    ]
