# Generated by Django 4.0.6 on 2022-07-27 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0006_remove_team_players_team_players'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='players',
            field=models.ManyToManyField(blank=True, help_text='players of the team', related_name='players', to='teams.player'),
        ),
    ]
