# Generated by Django 4.0.6 on 2022-08-08 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0007_alter_player_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='n_name',
            field=models.CharField(default='New Player', max_length=150, verbose_name='Nickname of the player'),
        ),
    ]
