# Generated by Django 4.0.6 on 2022-08-15 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0008_rename_team_player_player_team_team_leader'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='player_team',
            new_name='joined_team',
        ),
    ]
