# Generated by Django 4.0.6 on 2022-08-15 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0009_rename_player_team_player_joined_team'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='joined_team',
            new_name='team',
        ),
        migrations.RemoveField(
            model_name='team',
            name='leader',
        ),
    ]
