# Generated by Django 4.0.6 on 2022-08-17 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_remove_event_registered_players'),
        ('teams', '0010_rename_joined_team_player_team_remove_team_leader'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='events',
            field=models.ManyToManyField(blank=True, related_name='registered_players', to='events.event'),
        ),
    ]
