# Generated by Django 4.0.6 on 2022-07-28 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0011_alter_player_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='picture',
            field=models.ImageField(default='default.png', upload_to='profile_pics'),
        ),
    ]
