# Generated by Django 4.0.6 on 2022-08-18 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0011_player_events'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='emblem',
            field=models.ImageField(default='team_default.png', upload_to='team_pics/'),
        ),
        migrations.AlterField(
            model_name='player',
            name='picture',
            field=models.ImageField(default='default.png', upload_to='profile_pics/'),
        ),
    ]
