# Generated by Django 4.0.6 on 2022-07-28 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0012_player_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='games_played',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='picture',
            field=models.ImageField(default='profile_pics/defaulf.png', upload_to='profile_pics'),
        ),
    ]
