# Generated by Django 4.0.6 on 2022-07-28 16:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0014_alter_player_date_of_birth_alter_player_team_leader'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='team',
            field=models.ForeignKey(default='No Team', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team_players', to='teams.team'),
        ),
    ]
