# Generated by Django 4.0.6 on 2022-08-01 16:52

from django.db import migrations, models
import django.db.models.deletion
import teams.models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0016_alter_player_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='team',
            field=models.ForeignKey(default=teams.models.Team.get_default_pk, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team_players', to='teams.team'),
        ),
    ]
